void main() {
  String sehir = "İSTANBUL";
  String ulke = "Türkiye";
  int telefon = 5340000000;
  int posta_kodu = 34668;
  String email = "handeaygenli98@gmail.com";
  String meslek = "Fizikçi";
  int stok_miktari = 120;
  String musteri_adi = "Deniz";
  double bakiye = 1234.56;
  String dogum_gunu = "6 Temmuz";
  double maas = 12345678.90;
  String medeni_durum = "bekar";
  String urun_yorum = "kullanışlı";
  String odeme_tarihi = "12.12.2022";
  int odeme = 123;
  int siparis_adeti = 120;
  String araba_modeli = "Land Rover Defender";
  String kitap_adi = "Bir İdam Mahkumunun Son Günü";
  int yayinlanma_tarihi = 1829;
  String indirim_miktari = "%50";
  int oda_sayisi = 3;
  int enlem = 36;
  int boylam = 26;
  String urun_adi = "bilgisayar";
  double yemek_fiyati = 89.99;
  String marka = "marshall";
  String muzik_adi = "rock";
  double video_suresi = 12.12;
  double urun_puani = 4.9;
  double urun_fiyati = 49.99;
  String resim_adi = "Fırtınalı Deniz";
  String dosya_formati = "pdf";
  String renk = "turuncu";
  String renk_kodu = "FF7F00";
  String telefon_modeli = "samsung";
  double ekran_boyutu = 35.56;
  int agirlik = 3;
  String ulusal_gun = "29 Ekim Cumhuriyet Bayramı";
  String tatil_gunu = "1 Ocak";
  String rez_tarihi = "01.01.2023";
  String sokak_adi = "Begonvil sokak";
  int otobus_hatti = 12;
  int kalan_dakika = 987;
  int takip_kodu = 987654321;
  String kupon_suresi = "1 Hafta";
  int kupon_kodu = 12121212;
  String fatura_adresi = "Üsküdar İstanbul";

  print("Şehir : $sehir");
  print("Ülke : $ulke");
  print("Telefon : $telefon");
  print("Posta Kodu : $posta_kodu");
  print("e-mail : $email");
  print("Meslek : $meslek");
  print("Stok Miktarı : $stok_miktari");
  print("Müşteri Adı : $musteri_adi");
  print("Bakiye : $bakiye");
  print("Doğum Günü : $dogum_gunu");
  print("Maaş : $maas");
  print("Medeni Durum: $medeni_durum");
  print("Ürün Yorumu : $urun_yorum");
  print("Ürün Puanı : $urun_puani");
  print("Ödeme Tarihi : $odeme_tarihi");
  print("Ödeme : $odeme");
  print("Sipariş Adeti : $siparis_adeti");
  print("Araba Modeli : $araba_modeli");
  print("Kitap Adı : $kitap_adi");
  print("Yayınlanma Tarihi : $yayinlanma_tarihi");
  print("İndirim Miktarı : $indirim_miktari");
  print("Oda Sayısı : $oda_sayisi");
  print("Enlem : $enlem");
  print("Boylam : $boylam");
  print("Ürün Adı : $urun_adi");
  print("Yemek Fiyatı : $yemek_fiyati");
  print("Marka : $marka");
  print("Müzik Adı : $muzik_adi");
  print("Video Süresi : $video_suresi");
  print("Ürün Puanı : $urun_puani");
  print("Resim Adı : $resim_adi");
  print("Dosya Formatı : $dosya_formati");
  print("Renk : $renk");
  print("Renk Kodu : $renk_kodu");
  print("Telefon Modeli : $telefon_modeli");
  print("Ekran Boyutu : $ekran_boyutu");
  print("Ağırlık : $agirlik");
  print("Ulusal Gün : $ulusal_gun");
  print("Tatil Günü : $tatil_gunu");
  print("Rezervasyon Tarihi : $rez_tarihi");
  print("Sokak Adı : $sokak_adi");
  print("Otobüs Hattı : $otobus_hatti");
  print("Kalan Dakika : $kalan_dakika");
  print("Takip Kodu :$takip_kodu");
  print("Kupon SÜresi : $kupon_suresi");
  print("Kupon Kodu : $kupon_kodu");
  print("Fatura Adresi : $fatura_adresi");


}